global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: slack-notifications
  group_interval: 5s

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: 'test'
        text: |-
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Details:*
          {{ range .Labels.SortedPairs }} *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
          {{ end }}
        send_resolved: true